version: "3.7"
services:
  postgres:
    image: postgres:13-alpine
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: ib7
      POSTGRES_USER: ib7
      POSTGRES_PASSWORD: ib7
    volumes:
      - ./postgres/tables:/docker-entrypoint-initdb.d/

  ib7:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ib7
    init: true

    restart: on-failure

    env_file:
      - .env

    environment:
      - DATABASE_URL=postgres://ib7:ib7@postgres:5432/ib7

    volumes:
      - .:/bot

    depends_on:
      - postgres